"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.stringify = exports.isUndefined = exports.isDefined = exports.isString = exports.isRegExp = exports.isObject = exports.isNumber = exports.isError = exports.isEmpty = exports.isDate = exports.isBoolean = exports.isArray = exports.hasProperty = exports.extractAndRedact = exports.clone = exports.areEqual = exports.append = void 0;
var utils_1 = require("./utils");
Object.defineProperty(exports, "append", { enumerable: true, get: function () { return utils_1.append; } });
Object.defineProperty(exports, "areEqual", { enumerable: true, get: function () { return utils_1.areEqual; } });
Object.defineProperty(exports, "clone", { enumerable: true, get: function () { return utils_1.clone; } });
Object.defineProperty(exports, "extractAndRedact", { enumerable: true, get: function () { return utils_1.extractAndRedact; } });
Object.defineProperty(exports, "hasProperty", { enumerable: true, get: function () { return utils_1.hasProperty; } });
Object.defineProperty(exports, "isArray", { enumerable: true, get: function () { return utils_1.isArray; } });
Object.defineProperty(exports, "isBoolean", { enumerable: true, get: function () { return utils_1.isBoolean; } });
Object.defineProperty(exports, "isDate", { enumerable: true, get: function () { return utils_1.isDate; } });
Object.defineProperty(exports, "isEmpty", { enumerable: true, get: function () { return utils_1.isEmpty; } });
Object.defineProperty(exports, "isError", { enumerable: true, get: function () { return utils_1.isError; } });
Object.defineProperty(exports, "isNumber", { enumerable: true, get: function () { return utils_1.isNumber; } });
Object.defineProperty(exports, "isObject", { enumerable: true, get: function () { return utils_1.isObject; } });
Object.defineProperty(exports, "isRegExp", { enumerable: true, get: function () { return utils_1.isRegExp; } });
Object.defineProperty(exports, "isString", { enumerable: true, get: function () { return utils_1.isString; } });
Object.defineProperty(exports, "isDefined", { enumerable: true, get: function () { return utils_1.isDefined; } });
Object.defineProperty(exports, "isUndefined", { enumerable: true, get: function () { return utils_1.isUndefined; } });
Object.defineProperty(exports, "stringify", { enumerable: true, get: function () { return utils_1.stringify; } });
