export declare function isArray(value: any): boolean;
export declare function isBoolean(value: any): boolean;
export declare function isDate(value: any): boolean;
export declare function isEmpty(document: any): boolean;
export declare function isError(value: any): boolean;
export declare function isNumber(value: any): boolean;
export declare function isObject(value: any): boolean;
export declare function isRegExp(value: any): boolean;
export declare function isString(value: any): boolean;
export declare function isDefined(value: any): boolean;
export declare function isUndefined(value: any): boolean;
export declare function hasProperty(obj: any, property: string): boolean;
export declare function append(document: any, extensionDocument: any): any;
export declare function areEqual(firstObject: any, secondObject: any): boolean;
export declare function redactUndefinedValues(document: any): void;
export declare function clone(value: any, shouldRedactUndefinedValues?: boolean): any;
export declare function stringify(obj: any, indent?: number, linePrefix?: string, quoteFieldNames?: boolean): string;
export declare function extractAndRedact(document: any, propertyName: string): any;
